version: '2.1'
services:
    app:
        build: .
        container_name: converter
        volumes:
            - ./tmp/convert:/convert:rw
            - ./tmp/done:/done:rw
            - ./profiles:/app/profiles